import type { Metadata } from 'next';
import Image from 'next/image';
import { GUIDE, GUIDE_COVER_PATH } from '@peptide/shared';
import { GuideForm } from '@/components/guide/GuideForm';
import { CtaBand } from '@/components/marketing/Primitives';

export const metadata: Metadata = {
  title: 'The peptide guide',
  description:
    'A free guide to peptide therapy written by a doctor with no products to sell, what the evidence says, what you are actually buying, and the questions to ask before you start.',
};

const CONTENTS: [string, string][] = [
  ['Why this guide exists', 'Who writes peptide advice, and why that shapes what it says.'],
  ['What a peptide actually is', 'Why “do peptides work” is the wrong question.'],
  ['The three tiers of evidence', 'Licensed, researched, or anecdote, and how to tell.'],
  ['What you are actually buying', 'Why a vial bought online is not a medicine, and how to read a COA.'],
  ['How they are taken', 'Injection, nasal, topical, oral, and why the route changes the dose.'],
  ['Where the real risks are', 'Interactions, masking, technique. Rarely what people expect.'],
  [`${GUIDE.compounds} compounds, assessed`, 'Metabolic · repair · growth hormone · cognitive · sleep · immune.'],
  ['Questions before you start', 'If you cannot answer these, you are not ready.'],
  ['The boring answer that usually wins', 'What a doctor checks first.'],
];

const FACTS: [string, string][] = [
  ['Pages', String(GUIDE.pages)],
  ['Compounds', String(GUIDE.compounds)],
  ['Dosing protocols', 'None'],
  ['Products we sell', 'None'],
];

export default function GuidePage() {
  return (
    <>
      {/* Dark band: the cover is the product, so it is shown at full strength
          against ground that flatters it rather than dropped into the page. */}
      <section className="relative overflow-hidden bg-ink text-paper">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 opacity-90"
          style={{
            background:
              'radial-gradient(120% 90% at 12% 0%, rgb(23 96 138) 0%, rgb(var(--ink)) 48%, rgb(8 32 58) 100%)',
          }}
        />

        <div className="shell relative grid gap-14 py-16 sm:py-20 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)] lg:items-center lg:gap-20">
          <div>
            <p className="font-mono text-eyebrow uppercase tracking-[0.3em] text-brand-bright">
              Free guide · {GUIDE.pages} pages
            </p>
            <h1 className="mt-6 max-w-2xl font-display text-h1 font-light leading-[1.04] tracking-[-0.02em]">
              What a doctor would actually tell you about peptides.
            </h1>
            <p className="mt-7 max-w-xl text-lead font-light leading-relaxed text-paper/75">
              Almost everything written about peptides is written by someone selling them. This is
              not. It is written by a GMC-registered doctor with no products, no suppliers and no
              affiliate income, including the parts that say you probably should not take anything.
            </p>

            <dl className="mt-12 grid max-w-xl grid-cols-2 gap-x-8 gap-y-7 border-t border-paper/15 pt-8 sm:grid-cols-4 sm:gap-x-6">
              {FACTS.map(([label, value]) => (
                <div key={label}>
                  <dt className="font-mono text-[0.6rem] uppercase tracking-[0.18em] text-paper/50">
                    {label}
                  </dt>
                  <dd className="mt-2 font-display text-2xl font-normal">{value}</dd>
                </div>
              ))}
            </dl>
          </div>

          {/* Presented as a physical thing: leaves stacked behind, the cover
              lifted off them. It is the actual rendered PDF page, generated by
              the same script that writes the file, so it cannot go stale. */}
          <div className="relative mx-auto w-full max-w-sm lg:max-w-md">
            <div
              aria-hidden
              className="absolute inset-x-6 -bottom-2 top-6 rounded-sm bg-paper/10 blur-[1px]"
            />
            <div
              aria-hidden
              className="absolute inset-x-3 -bottom-1 top-3 rounded-sm bg-paper/20"
            />
            <Image
              src={GUIDE_COVER_PATH}
              alt={`Cover of the Peptide MD guide, ${GUIDE.pages} pages`}
              width={1588}
              height={2246}
              priority
              sizes="(max-width: 1024px) 24rem, 28rem"
              className="relative w-full rounded-sm shadow-[0_40px_80px_-24px_rgb(0_0_0/0.65)] ring-1 ring-paper/20"
            />
          </div>
        </div>
      </section>

      {/* Light band: what is inside, and the form to get it. */}
      <section className="shell py-16 sm:py-20">
        <div className="grid gap-12 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)] lg:gap-16">
          <div>
            <h2 className="font-display text-h2 font-medium tracking-[-0.02em] text-ink">
              What is inside
            </h2>

            <ol className="mt-8 grid gap-0 border-t border-line">
              {CONTENTS.map(([title, blurb], index) => (
                <li
                  key={title}
                  className="grid gap-1 border-b border-line py-4 sm:grid-cols-[3rem_1fr]"
                >
                  <span className="font-mono text-eyebrow uppercase tracking-[0.14em] text-muted">
                    {String(index + 1).padStart(2, '0')}
                  </span>
                  <span>
                    <span className="block text-sm font-medium text-ink">{title}</span>
                    <span className="mt-0.5 block text-micro leading-relaxed text-muted">
                      {blurb}
                    </span>
                  </span>
                </li>
              ))}
            </ol>
          </div>

          <aside className="lg:sticky lg:top-24 lg:self-start">
            <div className="rounded-lg border border-line bg-surface p-6 shadow-[0_1px_2px_rgb(var(--ink)/0.04),0_12px_32px_-16px_rgb(var(--ink)/0.16)] sm:p-8">
              <h2 className="font-display text-h3 font-medium text-ink">Send it to me</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted">
                {GUIDE.pages} pages, {GUIDE.compounds} compounds. Free, and yours to keep.
              </p>
              <div className="mt-6">
                <GuideForm source="guide-page" />
              </div>
            </div>
            <p className="mt-4 text-micro leading-relaxed text-muted">
              General information, not medical advice. Peptide MD does not supply, prescribe or
              dispense any compound.
            </p>
          </aside>
        </div>
      </section>

      <CtaBand
        title="Or skip the reading and ask the doctor directly."
        body="Twenty minutes, £95, and a straight answer about your own situation, including when the answer is that you should not be taking anything."
      />
    </>
  );
}
