-- Booking references were generated by reading the highest existing one and
-- adding one. Two checkouts starting in the same moment read the same value
-- and produced the same reference, so one of them failed on the unique index.
--
-- A sequence is atomic: every caller gets a distinct number regardless of
-- concurrency. Seeded above the existing data so live references never clash.
CREATE SEQUENCE IF NOT EXISTS booking_reference_seq AS BIGINT START WITH 4900;

SELECT setval(
  'booking_reference_seq',
  GREATEST(
    (SELECT COALESCE(MAX(NULLIF(regexp_replace(reference, '\D', '', 'g'), '')::BIGINT), 4900) FROM bookings),
    4900
  )
);
