/**
 * Generated by scripts/build-guide.mjs. Do not edit by hand.
 *
 * These numbers are read back out of the rendered PDF, so the marketing copy
 * and the file a lead actually receives cannot disagree.
 */
export const GUIDE = {
  pages: 21,
  compounds: 30,
  categories: 6,
} as const;

export const GUIDE_PDF_PATH = '/guides/peptide-md-guide.pdf';
export const GUIDE_COVER_PATH = '/guides/peptide-md-guide-cover.png';
